name: Build APK Offline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Android APK
        uses: GearS3/cordova-build-action@v1
        with:
          platform: android
          # Cela va créer un projet Cordova propre à la volée
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FantaroMG-Offline-APK
          path: ./**/*.apk
