name: Create APK File
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Android APK
        uses: un some-package/build-action@v2 # Un exemple de compilateur l√©ger
        with:
          args: --app-name "Fantaro MG" --package "com.nomena.fmg"
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FantaroMG-Offline-Installation
          path: ./*.apk
