name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Android APK
        uses: jpadilla/android-apk-build-action@v1
        with:
          build-command: ./gradlew assembleDebug # GitHub va essayer de deviner la structure

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FantaroMG-Offline
          path: ./**/*.apk
