name: Build APK
on: [push]
jobs:
  make_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Cordova
        run: npm install -g cordova

      - name: Setup Android Environment
        uses: android-actions/setup-android@v3

      - name: Build APK
        run: |
          cordova create build com.nomena.fmg "Fantaro MG"
          cd build
          cordova platform add android
          cp -r ../* www/
          cordova build android --debug

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Mon-Jeu-Offline
          path: build/platforms/android/app/build/outputs/apk/debug/*.apk
